version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8081:80'
    volumes:
      - ./public:/var/www/html/public

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
      
  database:
      image: 'mysql:latest'
      volumes:
          - ./mysql:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: main
      ports:
          # To allow the host machine to access the ports below, modify the lines below.
          # For example, to allow the host to connect to port 3306 on the container, you would change
          # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
          # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
          - '3306'
