version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8081:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
