version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8081:80'
    volumes:
      - ./public:/var/www/html/public

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
